server:
  port: 9334

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

io:
  lvdaxian:
    upload:
      file:
        enabled-type: disk
        delay-concurrency-merge-time: 1
        thread-sleep-time: 1